"""
Django settings for graphpilot project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import json
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from graphpilot import ports

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _runtime_frontend_origin():
    """The launcher's frontend origin, if a launcher is running.

    `run.py` writes this beside the repository while it holds its ports, because the MCP
    server is started by the IDE and shares no environment with it. Anything unreadable
    or unrecognised means "no launcher": a stale or hand-edited file must not be able to
    send a host to an arbitrary URL, and it must never stop Django starting.
    """
    try:
        payload = json.loads(
            (BASE_DIR.parent / ports.RUNTIME_FILENAME).read_text(encoding='utf-8')
        )
        origin = str(payload['frontendOrigin']).strip().rstrip('/')
    except (OSError, ValueError, KeyError, TypeError):
        return None
    return origin if origin.startswith(('http://localhost:', 'http://127.0.0.1:')) else None


# There were `_env_float` and `_env_int` helpers here, tolerating a malformed
# `AZURE_OPENAI_TIMEOUT` or projection budget rather than crashing startup. Every numeric
# setting they parsed went with the provider pipeline, and they outlived it uncalled.
# Nothing below needs them: the six settings that remain are strings and one boolean.

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')
if not DEBUG and SECRET_KEY in {'django-insecure-dev-only', 'replace-with-a-secret-key'}:
    raise ImproperlyConfigured('Set a strong DJANGO_SECRET_KEY when DJANGO_DEBUG is false.')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'operations',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'graphpilot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'graphpilot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# CORS
# https://github.com/adamchainz/django-cors-headers

# Origins allowed to call the API — configured entirely via the environment
# (GRAPHPILOT_CORS_ALLOWED_ORIGINS, comma-separated); nothing is hardcoded here.
# Note: `localhost` and `127.0.0.1` are distinct origins for CORS; list every
# frontend origin you use in the .env (the repo's Vite config uses strict port 5173).
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('GRAPHPILOT_CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]


# Django REST Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}


# GraphPilot-specific settings

# There was a GRAPHPILOT_DEFAULT_WORKSPACE_DIR here, read by nothing. Every MCP tool
# takes `workspaceDir` per call, which is the design: a host says which repository it
# is diagramming, and a default would have nothing to default to.
GRAPHPILOT_STORAGE_DIR = os.environ.get('GRAPHPILOT_STORAGE_DIR', '.graphpilot')
# Base URL of the React frontend, used by the MCP tools to build the returned editUrl
# (`<base>/editor?diagramPath=<path>`).
#
# Two things can be running: the hand-started dev server, and the double-clicked
# launcher on its own ports. Setting this to a *third* place pins the answer; leaving it
# at the dev origin (or empty) lets `services.shared.editor_origin` resolve which of the
# two is actually up.
#
# `.env` describes the **dev** setup — that is what its CORS line and the frontend's
# `VITE_API_BASE_URL` are for — so a value that simply *is* the dev origin is the
# template speaking, not a decision. Treating it as a pin is what broke this first: every
# install shipped `=http://localhost:5173`, so the resolver never ran and anyone using
# only the launcher got a well-formed link to a port nothing was serving.
_frontend_base_url = os.environ.get('GRAPHPILOT_FRONTEND_BASE_URL', '').strip().rstrip('/')
GRAPHPILOT_FRONTEND_BASE_URL_EXPLICIT = (
    _frontend_base_url if _frontend_base_url != ports.dev_frontend_origin() else ''
)
GRAPHPILOT_FRONTEND_BASE_URL = _frontend_base_url or ports.dev_frontend_origin()

# Written by `run.py` while the launcher is running, so the IDE-spawned MCP server — a
# process the launcher never started — can discover which port the app actually got.
GRAPHPILOT_RUNTIME_FRONTEND_ORIGIN = _runtime_frontend_origin()
# The diagram file extension (".gp.json") + empty-name fallback ("diagram") are
# owned by WorkspaceStorageService's built-in default; no setting/env var is needed
# (diagram names come from the MCP/LLM/prompt, not config).

# GraphPilot makes no provider calls. The host authors a diagram draft and the
# backend materializes it deterministically, so there is no endpoint, key,
# deployment, timeout, reasoning effort, projection budget, few-shot count, or
# review mode to configure.


# Logging — surface backend warnings/errors to stderr for debuggability. stderr (not
# stdout) is used so the MCP stdio transport's protocol stream stays clean.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {'simple': {'format': '%(levelname)s %(name)s: %(message)s'}},
    'handlers': {'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}
